name = "SteerableConvolutions"
uuid = "32a0adf6-ff23-49da-a88f-3a4282d64f1a"
authors = ["Syver Døving Agdestein <syverda@gmail.com> and contributors"]
version = "1.0.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
EnumX = "4e289a0a-7415-4d19-859d-a7e5c4648b56"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"

[compat]
DocStringExtensions = "0.9"
EnumX = "1"
LinearAlgebra = "1"
Lux = "0.5"
TensorOperations = "5"
julia = "1.10"
