name = "SteerableConvolutions"
uuid = "32a0adf6-ff23-49da-a88f-3a4282d64f1a"
authors = ["Syver Døving Agdestein <syverda@gmail.com> and contributors"]
version = "1.0.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
DocStringExtensions = "0.9.3"
LinearAlgebra = "1.11.0"
Lux = "0.5"
SparseArrays = "1.11.0"
julia = "1.10"
