name = "Examples"
uuid = "ee9a67c0-c934-4b7d-bf63-3a54c792bd50"
authors = ["Syver Døving Agdestein <syverda@gmail.com>"]
version = "1.0.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
SteerableConvolutions = "32a0adf6-ff23-49da-a88f-3a4282d64f1a"

[compat]
CairoMakie = "0.12"
SteerableConvolutions = "1"
julia = "1.10"

[sources]
SteerableConvolutions = {path = ".."}
