name = "Examples"
uuid = "ee9a67c0-c934-4b7d-bf63-3a54c792bd50"
authors = ["Syver Døving Agdestein <syverda@gmail.com>"]
version = "1.0.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
SteerableConvolutions = "32a0adf6-ff23-49da-a88f-3a4282d64f1a"

[sources]
SteerableConvolutions = {path = ".."}

[compat]
CairoMakie = "0.12"
FileIO = "1"
ImageIO = "0.6"
ImageMagick = "1"
Images = "0.26"
SteerableConvolutions = "1"
julia = "1.10"
